# Question bank
# To add more questions go to https://opentdb.com/


questions_bank = [

    # General knowledge questions:

    # Easy difficulty questions
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which best selling toy of 1983 caused hysterias, resulting in riots "
                 "breaking out in stores?",
     "correct_answer": "Cabbage Patch Kids",
     "incorrect_answers": ["Transformers", "Care Bears", "Rubik&rsquo;s Cube"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Area 51 is located in which US state?", "correct_answer": "Nevada",
     "incorrect_answers": ["Arizona", "New Mexico", "Utah"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What word represents the letter &#039;T&#039; in the NATO phonetic "
                 "alphabet?",
     "correct_answer": "Tango", "incorrect_answers": ["Target", "Taxi", "Turkey"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of the Jewish New Year?",
     "correct_answer": "Rosh Hashanah",
     "incorrect_answers": ["Elul", "New Year", "Succoss"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is on display in the Madame Tussaud&#039;s museum in London?",
     "correct_answer": "Wax sculptures",
     "incorrect_answers": ["Designer clothing", "Unreleased film reels", "Vintage cars"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What was the nickname given to the Hughes H-4 Hercules, a heavy "
                 "transport flying boat which achieved "
                 "flight in 1947?",
     "correct_answer": "Spruce Goose",
     "incorrect_answers": ["Noah&#039;s Ark", "Fat Man", "Trojan Horse"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Five dollars is worth how many nickles?", "correct_answer": "100",
     "incorrect_answers": ["50", "25", "69"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "How tall is the Burj Khalifa?", "correct_answer": "2,722 ft",
     "incorrect_answers": ["2,717 ft", "2,546 ft", "3,024 ft"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "The likeness of which president is featured on the rare $2 bill of USA currency?",
     "correct_answer": "Thomas Jefferson",
     "incorrect_answers": ["Martin Van Buren", "Ulysses Grant", "John Quincy Adams"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of NASA&rsquo;s most famous space telescope?",
     "correct_answer": "Hubble Space Telescope",
     "incorrect_answers": ["Big Eye", "Death Star", "Millenium Falcon"]},

    # Medium difficulty questions
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "This field is sometimes known as &ldquo;The Dismal Science.&rdquo;",
     "correct_answer": "Economics",
     "incorrect_answers": ["Philosophy", "Politics", "Physics"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "In a standard set of playing cards, which is the only king without a moustache?",
     "correct_answer": "Hearts", "incorrect_answers": ["Spades", "Diamonds", "Clubs"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Which river flows through the Scottish city of Glasgow?",
     "correct_answer": "Clyde", "incorrect_answers": ["Tay", "Dee", "Tweed"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "What is the defining characteristic of someone who is described as hirsute?",
     "correct_answer": "Hairy", "incorrect_answers": ["Rude", "Funny", "Tall"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "What was the destination of the missing flight MH370?",
     "correct_answer": "Beijing",
     "incorrect_answers": ["Kuala Lumpur", "Singapore", "Tokyo"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "What country saw a world record 315 million voters turn out for elections on May 20, 1991?",
     "correct_answer": "India",
     "incorrect_answers": ["United States of America", "Soviet Union", "Poland"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "According to the United States&#039; CDC, one in how many Americans die annually due to smoking?",
     "correct_answer": "Five", "incorrect_answers": ["Twenty", "Ten", "One hundred"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Which item of clothing is usually worn by a Scotsman at a wedding?",
     "correct_answer": "Kilt", "incorrect_answers": ["Skirt", "Dress", "Rhobes"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "In ancient Greece, if your job were a &quot;hippeus&quot; which of these would you own?",
     "correct_answer": "Horse", "incorrect_answers": ["Weave", "Guitar", "Boat"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "What fast food chain has the most locations globally? ",
     "correct_answer": "Subway", "incorrect_answers": ["Starbucks", "McDonalds", "KFC"]},

    # Hard difficulty questions
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "The words &quot;bungalow&quot; and &quot;shampoo&quot; originate from the languages of which country?",
     "correct_answer": "India",
     "incorrect_answers": ["Papua New Guinea", "Ethiopia", "China"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "When was &quot;YouTube&quot; founded?",
     "correct_answer": "February 14, 2005",
     "incorrect_answers": ["May 22, 2004", "September 12, 2005", "July 19, 2009"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "How long did it take the motorized window washers of the original World Trade Center to clean the "
                 "entire exterior of the building?",
     "correct_answer": "1 Month", "incorrect_answers": ["3 Weeks", "1 Week", "2 Months"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "What does the Latin phrase &quot;Veni, vidi, vici&quot; translate into English?",
     "correct_answer": "I came, I saw, I conquered",
     "incorrect_answers": ["See no evil, hear no evil, speak no evil",
                           "Life, liberty, and happiness", "Past, present, and future"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which church&#039;s interior in Vatican City was designed in 1503 by renaissance architects "
                 "including Bramante, Michelangelo and Bernini?",
     "correct_answer": "St. Peter&#039;s Basilica",
     "incorrect_answers": ["Catania Cathedral", "St. Mark&rsquo;s Basilica",
                           "The Duomo of Florence"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "What is the most commonly used noun in the English language?",
     "correct_answer": "Time", "incorrect_answers": ["Home", "Water", "Man"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "The word &quot;abulia&quot; means which of the following?",
     "correct_answer": "The inability to make decisions",
     "incorrect_answers": ["The inability to stand up",
                           "The inability to concentrate on anything",
                           "A feverish desire to rip one&#039;s clothes off"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which of these cities does NOT have a United States Minting location?",
     "correct_answer": "St. Louis, MO",
     "incorrect_answers": ["San Fransisco, CA", "Philidelphia, PA", "West Point, NY"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following is not another name for the eggplant?",
     "correct_answer": "Potimarron",
     "incorrect_answers": ["Brinjal", "Guinea Squash", "Melongene"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "In &quot;Resident Evil 3&quot;, how many inventory slots does Jill have at the start of the game?",
     "correct_answer": "10", "incorrect_answers": ["6", "8", "12"]},


    # Geography questions

    # Easy difficulty questions
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "What year was Queen Elizabeth II born?", "correct_answer": "1926",
     "incorrect_answers": ["1923", "1929", "1930"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which of these banks are NOT authorized to issue currency notes in Hong Kong?",
     "correct_answer": "OCBC",
     "incorrect_answers": ["HSBC", "Standard Chartered", "Bank of China"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "The Swedish word &quot;Grunka&quot; means what in English?",
     "correct_answer": "Thing", "incorrect_answers": ["People", "Place", "Pineapple"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "How long did it take the motorized window washers of the original World Trade Center to clean the "
                 "entire exterior of the building?",
     "correct_answer": "1 Month", "incorrect_answers": ["3 Weeks", "1 Week", "2 Months"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following languages does NOT use gender as a part of its grammar?",
     "correct_answer": "Turkish", "incorrect_answers": ["German", "Danish", "Polish"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "What was Bank of America originally established as?",
     "correct_answer": "Bank of Italy",
     "incorrect_answers": ["Bank of Long Island", "Bank of Pennsylvania",
                           "Bank of Charlotte"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Virtual reality company Oculus VR lost which of it&#039;s co-founders in a freak car accident in "
                 "2013?",
     "correct_answer": "Andrew Scott Reisse",
     "incorrect_answers": ["Nate Mitchell", "Jack McCauley", "Palmer Luckey"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Named after the mallow flower, mauve is a shade of what?",
     "correct_answer": "Purple", "incorrect_answers": ["Red", "Brown", "Pink"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "The word &quot;abulia&quot; means which of the following?",
     "correct_answer": "The inability to make decisions",
     "incorrect_answers": ["The inability to stand up",
                           "The inability to concentrate on anything",
                           "A feverish desire to rip one&#039;s clothes off"]},

    # Medium difficulty questions:
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of the former country that was succeeded by countries such as Serbia, Croatia and "
                 "Slovenia?",
     "correct_answer": "Yugoslavia",
     "incorrect_answers": ["Czechoslovakia", "Abkhazia", "South Ossetia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What are the four corner states of the US?",
     "correct_answer": "Utah, Colorado, Arizona, New Mexico",
     "incorrect_answers": ["Oregon, Idaho, Nevada, Utah",
                           "Kansas, Oklahoma, Arkansas, Louisiana",
                           "South Dakota, Minnesota, Nebraska, Iowa"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "The following Spanish provinces are located in the northern area of Spain except:",
     "correct_answer": "Murcia",
     "incorrect_answers": ["Asturias", "Navarre", "Le&oacute;n"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "All of the following countries have official claims to territory in Antartica EXCEPT:",
     "correct_answer": "United States",
     "incorrect_answers": ["Australia", "Chile", "Norway"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "How many countries does Spain have a land border with?",
     "correct_answer": "5", "incorrect_answers": ["2", "3", "4"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What tiny principality lies between Spain and France?",
     "correct_answer": "Andorra",
     "incorrect_answers": ["Liechtenstein", "Monaco", "San Marino"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which country has the abbreviation &quot;CH&quot;?",
     "correct_answer": "Switzerland",
     "incorrect_answers": ["China", "Canada", "No Country"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "How many independent countries are there within the continent of South America?",
     "correct_answer": "12", "incorrect_answers": ["8", "9", "10"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of the only remaining Grand Duchy in the world ?",
     "correct_answer": "Luxembourg",
     "incorrect_answers": ["Montenegro", "Liechtenstein", "Andorra"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "How many time zones are in Russia?", "correct_answer": "11",
     "incorrect_answers": ["8", "5", "2"]},

    # Hard difficulty questions
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "In which city, is the Big Nickel located in Canada?",
     "correct_answer": "Sudbury, Ontario",
     "incorrect_answers": ["Calgary, Alberta", "Halifax, Nova Scotia ",
                           "Victoria, British Columbia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "Which of these island countries is located in the Caribbean?",
     "correct_answer": "Barbados",
     "incorrect_answers": ["Fiji", "Maldives", "Seychelles"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "Fucking is a village in which country?", "correct_answer": "Austria",
     "incorrect_answers": ["Germany", "Switzerland", "Czech Republic"]},
    {"category": "Geography", "type": "boolean", "difficulty": "hard",
     "question": "Switzerland has four national languages, English being one of them.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the name of the Canadian national anthem?",
     "correct_answer": "O Canada",
     "incorrect_answers": ["O Red Maple", "Leaf-Spangled Banner",
                           "March of the Puck Drop"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the land connecting North America and South America?",
     "correct_answer": "Isthmus of Panama",
     "incorrect_answers": ["Isthmus of Suez", "Urals", "Australasia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the most common climbing route for the second highest mountain in the world, K2?",
     "correct_answer": "Abruzzi Spur",
     "incorrect_answers": ["Magic Line", "Cesen Route", "Polish Line"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "Which country is the Taedong River in?", "correct_answer": "North Korea",
     "incorrect_answers": ["South Korea", "Japan", "China"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "Which is not a country in Africa?", "correct_answer": "Guyana",
     "incorrect_answers": ["Senegal", "Liberia", "Somalia"]}
]

